version: 2

sources:
  - name: silver
    database: FINANCIAL_DB
    schema: SILVER
    tables:
      - name: clean_transactions
        description: "Cleaned and enriched transactions from Bronze CDC pipeline"